name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build the project
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: |
            dist
            package.json
          if-no-files-found: error

  deploy:
    name: Deploy to Build Branch
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: production-files

      - name: Move artifact files to a temporary directory
        run: |
          mkdir -p /tmp/build_artifacts
          mv dist /tmp/build_artifacts/ || echo "No dist directory found in artifact"
          mv package.json /tmp/build_artifacts/ || echo "No package.json found in artifact"

      - name: Deploy to build branch
        run: |
          # Configure Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Fetch and switch to the build branch
          git fetch origin build || echo "No existing build branch found"
          git checkout build || git checkout --orphan build

          # Clear the build branch
          git rm -rf . || echo "Nothing to remove, starting from an empty branch"

          # Restore files from the temporary directory
          cp -r /tmp/build_artifacts/dist/* ./ || echo "No dist files to copy"
          cp /tmp/build_artifacts/package.json ./ || echo "No package.json file to copy"

          # Stage and commit changes
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Build and deploy to build branch"
            git push -f origin build
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
