name: Build and Deploy to Build Branch

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]  # Test across multiple Node.js versions

    steps:
      # Step 1: Check out repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project
      - name: Build the project
        run: npm run build --if-present

      # Step 5: Prepare files for the build branch
      - name: Prepare files for deployment
        run: |
          mkdir output
          cp -r dist/* output/
          cp package.json output/

      # Step 6: Push to build branch
      - name: Push to build branch
        if: success()  # Only deploy if the build and tests succeed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b build
          git add -f output/*
          git commit -m "Build and deploy to build branch"
          git push -f origin build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
