name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Required to push changes to the build branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Ensure only the provided token is used
          fetch-depth: 0              # Allow pushing refs without errors

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Prepare the build branch
      - name: Prepare build branch
        run: |
          # Configure Git user for commits
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Switch to the build branch or create it if it doesn't exist
          if git show-ref --quiet refs/heads/build; then
            git checkout build
          else
            git checkout --orphan build
          fi

          # Clean the branch and prepare for new files
          git rm -rf . || echo "Nothing to remove"
          mkdir -p dist

          # Copy the build files into the current directory
          cp -r dist/* . || echo "No dist files to copy"
          cp package.json . || echo "No package.json file to copy"

      # Step 6: Push to build branch
      - name: Push changes to build branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build          # Target branch
          force: true            # Force push to overwrite existing content
          directory: .           # Push files from the current directory
