name: Build and Deploy to Build Branch

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Verify files before upload
      - name: Verify build files
        run: |
          ls -la
          ls -la dist

      # Step 6: Upload production-ready build files
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: |
            dist
            package.json
          if-no-files-found: error  # Fail if files are missing

  deploy:
    name: Deploy to Build Branch
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Download the build artifact
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: production-files

      # Step 3: Verify downloaded files
      - name: Verify downloaded files
        run: |
          echo "Root directory contents:"
          ls -la
          echo "Contents of dist directory:"
          ls -la dist || echo "dist directory does not exist"

      # Step 4: Deploy to build branch
      - name: Deploy to build branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch
          git checkout build || git checkout --orphan build
          git reset --hard
          git clean -fdx
          mv dist/* . || echo "No dist files to move"
          mv package.json . || echo "No package.json file to move"
          git add .
          git commit -m "Build and deploy to build branch"
          git push -f origin build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
